FORMAT: 1A
HOST: https://api.ursa.cc

# ursa

Ursa is test, everything below is more testing.

## Auth [/auth]

### Get current session [GET]

+ Response 200 (application/json)

         {
            "user": {
                "x": "y"
            }
        }
        
+ Response 403 (application/json)

        {
            "error":"Authorization is required for request on GET /auth",
            "status":401,
            "response":null
        }